version: '3.8'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - app-net

  service_1:
    build:
      context: ./service_1
    expose:
      - "8001"
    networks:
      - app-net

  service_2:
    build:
      context: ./service_2
    expose:
      - "8002"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

